### ISSUE TITLE
Make use of the barometer on the device

### ISSUE THREAD

**Issue by sergimn** [woheller69/eggtimer#1]
Some devices have a barometer sensor built in. If the app used it the location permission wouldn't be mandatory and the barometer would provide better precision when it comes to computing how much time is needed. 
Not all devices have it so there should be a fallback to using GPS

**Comment by woheller69** [comment]
Good idea, but I do not have a phone with pressure sensor. A GPS should be available in every phone and accuracy also for altitude is quite high. Even +/-50m does not make a big difference for this application.
Will consider once I get a phone with pressure sensor.

**Comment by H34dl3ss** [comment]
Please also allow to enter pressure or altitude manually in case no GPS is available.

**Comment by woheller69** [comment]
There was a "," instead of a "." in the lookup table at 1013.25 mbar.

Should work now

[Eggtimer_pressure_fix.apk.zip](https://github.com/woheller69/eggtimer/files/9977690/Eggtimer_pressure_fix.apk.zip)

**Comment by woheller69** [comment]
-> V2.5
