### ISSUE TITLE
Possibility to specify altitude manually

### ISSUE THREAD

**Issue by bjmdev** [woheller69/eggtimer#14]
Dear woheller69,

Simply for conveniene it would be nice if one could specify the required altitude manually instead of waiting on the balkony for a gps fix. The latter is extremely inconvinient at home where altitude is known anyway.

I would propose a simple text field above the size choice with a switch for gps<-->manual height.

Thank you and best wishes
bjmdev

**Comment by woheller69** [comment]
I think what I will do is save the latest altitude in a preference and use this until a new altitude is provided from GPS
