### ISSUE TITLE
App Does Not Specify Avian Sources

### ISSUE THREAD

**Issue by h-town** [woheller69/eggtimer#15]
I cooked an ostrich egg using the XL specification and ended up making a gooey mess of my kitchen.

**Comment by woheller69** [comment]
I didn't know the EU XL specification also applies to ostrich eggs :-)
What is the weight of this egg? If you like I can compile a special version for you with several ostrich egg sizes.
Maybe the formula works as well.
Cooking will probably take an hour or more.

**Comment by rstruminski** [comment]
Hahaha, or simply rename the app "Smart CHICKEN egg timer" - issue solved! 😂
