### ISSUE TITLE
[Enhancement] Save known places/heights

### ISSUE THREAD

**Issue by rstruminski** [woheller69/eggtimer#16]
Cute little app! My breakfast eggs are just _perfect_ since I use it! 🙂 This app makes me happy. ♥️

**Suggestion:** Since one usually boils one's eggs at the same place, it would be useful if the last detected height/altitude would automatically be saved and used the next time you start the app. That way you wouldn't have to enable GPS and wait for a signal every day, but instead simply use the same height that you used yesterday.

Or even add an option to save different detected heights as "favorite places".

**Comment by woheller69** [comment]
Save last height is implemented. Coming soon

**Comment by rstruminski** [comment]
Oh sorry, my bad... Didn't see that.
Wonderful, thanks!

**Comment by woheller69** [comment]
just relased the update. It will take a few days until it is through F-Droid.
