### ISSUE TITLE
Please also add EierML as algorithm of possible

### ISSUE THREAD

**Issue by mmoole** [woheller69/eggtimer#17]
EierML is an app made by students using Machine Learning and they kind of verified the results, and it is open source, so it should be possible to add the calculations thus having the option to choose which formula to use for the user.
https://eierml.ml-projects.de/ 

greetings

**Comment by woheller69** [comment]
I have not seen an algorithm there. A simple linear regression will not work. Also they will need to cook a few thousand eggs more at different altitudes...
