### ISSUE TITLE
Explain boiling instruction better 

### ISSUE THREAD

**Issue by tobiasKaminsky** [woheller69/eggtimer#18]
Hi,

Thanks for your app!
While reading the instructions, I am unsure if the water needs to boil all the time, or if it enough to only have it boiling once and then the water cools down while heating up the egg.

I even looked into the formula, but still am unsure.

Thanks again for your app!

**Comment by woheller69** [comment]
needs to be boiling all the time. Must keep max possible water temperature for current altitude
