### ISSUE TITLE
Enter the weight of the egg 

### ISSUE THREAD

**Issue by johannesm987** [woheller69/eggtimer#2]
Would it be possible to add the feature, that one can enter the weight of the egg instead of the size (S, M, ...).
If you get your eggs direct from a little farmer, they often have different sizes in one package.

**Comment by woheller69** [comment]
will consider it for a future release.

For the time being you can set the size according to measured weight as follows:

    S <53g
    M 53...63g
    L 63...73g
    XL >73g
