### ISSUE TITLE
Request for manual height insertion

### ISSUE THREAD

**Issue by 1661410107114145152525** [woheller69/eggtimer#24]
Thank you very much for that app! The GPS height determination does not work on my phone - furthermore I do not want to turn it on, because I know the height or can google it within a second.

Please give us the possibility to enter the height manual. Thanks a lot! :)

**Comment by woheller69** [comment]
Please try. Remove .zip and install.
Click on altitude to set value. It will complain about missing GPS but it should work
[app-release.apk.zip](https://github.com/woheller69/eggtimer/files/8456302/app-release.apk.zip)

**Comment by 1661410107114145152525** [comment]
Thank you for the apk, but I will wait for an official update via F-Droid, sorry.

**Comment by 1661410107114145152525** [comment]
Thank you very much for the latest update, it works like a charm! Next time 
cooking eggs during vacation your app will replace my hardware gadget egg 
:). Thanks!

Am 9. April 2022 07:17:25 schrieb woheller69 ***@***.***>:
