### ISSUE TITLE
The 'pierce eggs' could perhaps use extra explaining or boilerplate

### ISSUE THREAD

**Issue by Mrnofish** [woheller69/eggtimer#26]
Having cooked eggs for many years with more than satisfactory results, I was somewhat curious about the piercing and the aim it should be achieving, as I didn't remember hearing that particular tip before.

So I went to my trusty search engine, and found out that the reason appears to be easier peeling and/or because the eggs don't crack as easily.

OTOH there seem to be food safety guidelines recommending against piercing eggs before cooking - if I had to take a guess, it's probably a non-issue for EU users, as my understanding is the safety requirements are more stringent there.

I seem to recall food safety standards are more relaxed in the US (e.g. see FDA temperature guidelines for patties and chicken meat), so introducing salmonella to the egg might be a legit concern especially for soft eggs where the cooking time might become insufficient to destroy the contaminant.

The likelihood of getting sued might be remote (at least that's my hope), nevertheless I thought it may be worth adjusting the instructions.

While I could not find anything on the FDA site against piercing, Wikipedia features a relevant wayback machine note:

> The American Egg Board, an industry group, recommends against piercing shells on food safety grounds: "Piercing shells before cooking is not recommended. If not sterile, the piercer or needle can introduce bacteria into the egg. Also, piercing creates hairline cracks in the shell through which bacteria can enter after cooking.",

**Comment by woheller69** [comment]
Without piercing the egg will break if you put it in boiling water, at least with high probability.
The position where you potentially introduce bacteria is close to the surface. There bacteria will be killed even for a soft egg.

**Comment by Mrnofish** [comment]
Well it's good you are so self-assured about all of that. It's your name on the tin, after all. Off into the setting sun!

**Comment by woheller69** [comment]
Maybe I should add that people washing their cats in the dish washer should not use this app :-)

**Comment by woheller69** [comment]
"If not sterile, the piercer or needle can introduce into the egg"
The highest risk for sure comes from the egg and not from the piercer or needle.
I should rather add "Use surgical gloves when touching the egg" :-)
