### ISSUE TITLE
Define temperatures for (soft/medium/hard)

### ISSUE THREAD

**Issue by henzelen** [woheller69/eggtimer#27]
Awesome App! Have been looking forward to the manual altitude update! Thanks!

Would love the option to choose own values for soft/medium/hard in the future, so you don't have to remember your favorite temperature settings

Also would be cool to start multiple alarms at once. I find myself in the situation quite often that I want to have 2 eggs soft and 4 hard for example

**Comment by woheller69** [comment]
Please try. Remove .zip and install.
You can set your favorite temperatures for soft, medium, hard.
[app-release.apk.zip](https://github.com/woheller69/eggtimer/files/8747106/app-release.apk.zip)

**Comment by henzelen** [comment]
Awesome! Thanks :)
