### ISSUE TITLE
Missing GPS Loop

### ISSUE THREAD

**Issue by 1661410107114145152525** [woheller69/eggtimer#29]
Latest update causes freezing in a loop of toast notifications that GPS is missing. I can't even access the settings or edit the height manually.

Thanks a lot for your amazing app! :)

**Comment by woheller69** [comment]
There should not be a loop. You may need to wait a few seconds without doing something and then go to settings.
Are you using GPS or do you want to use manual altitude?
If you have a pressure sensor you can also try the version in the barometer issue.

**Comment by woheller69** [comment]
I could reproduce it. You denied GPS and said don't ask again, right?
Go to Android settings, allow GPS  for the apl there for a moment.
Then open app and switch it off in there. Then you can revoke the permission

**Comment by woheller69** [comment]
Can you please try this version?

-Uninstall old version
-Remove .zip from filename
-Install

[app-release.apk.zip](https://github.com/woheller69/eggtimer/files/9996550/app-release.apk.zip)

**Comment by woheller69** [comment]
-> V2.5

**Comment by 1661410107114145152525** [comment]
Perfect, thank you! :)

Am 19. Dezember 2022 09:54:33 schrieb woheller69 ***@***.***>:
