### ISSUE TITLE
[wish] ability to choose alarm sound

### ISSUE THREAD

**Issue by andrearicci** [woheller69/eggtimer#31]
I normally have the alarm sound to allow a nice weak up. Pretty soft with increasing volume. So it's not good for the timer. It would be nice the possibility to choose another sound.
Thank you

**Comment by woheller69** [comment]
I added an internal alarm sound. Please try.  (switch on in options)

-uninstall old app
-remove .zip from filename
-install

[app-release.apk.zip](https://github.com/woheller69/eggtimer/files/10477914/app-release.apk.zip)

**Comment by andrearicci** [comment]
I like it! (still I would like to be able to choose mine)
Thank you

**Comment by woheller69** [comment]
I will not go beyond that. A file chooser adds complexity due to required permissions and will cause trouble with every new Android release when Google changes requirements

**Comment by andrearicci** [comment]
Very clear.
Thank you
