### ISSUE TITLE
Problem with Garmin Smartwatch constantly generating new notifications

### ISSUE THREAD

**Issue by xCaradhras** [woheller69/eggtimer#37]
Hi!

I like your app very much and cooked a lot of perfect eggs with it :) 

But there is one issue I have with it: Your app seems to update / recreate the notification every second.
This is interpreted by the smartwatch integration as a "new" notification, resulting in a vibration and a "popup". This means that during the time of cooking an egg my smartwatch is constantly vibrating and popping up a new notification. I cant even read the new notification, as it will pop up again.

As my knowledge of the inner workings of Android Notification system and the smartphone integration is more or less non-existant I unfortunately cannot point you in any direction. :( But I am happy to provide more info or test any possible solution, if it is of any help.

Smartphone Sony Xperia 5 III (Android 13)
Smartwatch Garmin Forerunner 55

Best regards!

**Comment by woheller69** [comment]
yes, the notification is updated every second.
On Android 13 you can disable notifications for this app in Android settings
