### ISSUE TITLE
Countdown stops when display off or app in the background

### ISSUE THREAD

**Issue by Stane01** [woheller69/eggtimer#39]
On my old smartphone the app worked fine but on my Pixel 8 Pro (Android 14) in spite of the notification the countdown stops a few minutes after the app went in the background the display got dark. All permissions are granted.

**Comment by woheller69** [comment]
With display off and app in **foreground** it works for me on Android 14. 
In background the countdown stops but the alarm still fires when the time is up. And if you open the app the countdown continues.
Unfortunately removing battery optimization for the app does not seem to help anymore.

**Comment by woheller69** [comment]
Please try this version and let me know if it works.

-Uninstall
-Remove .zip and install

[app-release.apk.zip](https://github.com/user-attachments/files/16669782/app-release.apk.zip)

**Comment by woheller69** [comment]
Did you try it?
