### ISSUE TITLE
Add extra info

### ISSUE THREAD

**Issue by aha999** [woheller69/eggtimer#6]
A button with extra info in a corner of the app (or where the text is below the egg) or simply some text below the egg that would describe additional information like:
- the sizes of eggs and dimensions of such eggs; how big/heavy is L... etc.
- what does the temperature mean? Temperature of the egg ? Of the fridge where the egg was? There's places where a room temp. Is 20-30°C or more if stored on a shelf
-should water be boiling ?

**Comment by woheller69** [comment]
The text below the app says that water should be boiling.

The egg sizes are as defined by rhe EU.
S <53g
M 53...63g
L 63...73g
XL >73g
